"""Add user profiles and matching system tables

Revision ID: c32513a76a07
Revises: ee79478097c6
Create Date: 2025-06-28 02:45:17.884605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32513a76a07'
down_revision = 'ee79478097c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('min_investment', sa.Integer(), nullable=True),
    sa.Column('max_investment', sa.Integer(), nullable=True),
    sa.Column('preferred_industries', sa.Text(), nullable=True),
    sa.Column('investment_stage', sa.Text(), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('geographic_preference', sa.Text(), nullable=True),
    sa.Column('team_size_preference', sa.String(length=20), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('previous_investments', sa.Integer(), nullable=True),
    sa.Column('expertise_areas', sa.Text(), nullable=True),
    sa.Column('mentoring_available', sa.Boolean(), nullable=True),
    sa.Column('follow_on_investment', sa.Boolean(), nullable=True),
    sa.Column('co_investment_preferred', sa.Boolean(), nullable=True),
    sa.Column('board_participation', sa.Boolean(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('investor_interest', sa.String(length=20), nullable=True),
    sa.Column('startup_interest', sa.String(length=20), nullable=True),
    sa.Column('match_reasons', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('industry_match_score', sa.Float(), nullable=True),
    sa.Column('funding_stage_score', sa.Float(), nullable=True),
    sa.Column('geographic_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('market_size_score', sa.Float(), nullable=True),
    sa.Column('investor_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('startup_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=10), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startup_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('business_model', sa.String(length=50), nullable=True),
    sa.Column('target_market', sa.Text(), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('company_stage', sa.String(length=20), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('funding_needed', sa.Integer(), nullable=True),
    sa.Column('funding_stage', sa.String(length=20), nullable=True),
    sa.Column('current_valuation', sa.Integer(), nullable=True),
    sa.Column('monthly_revenue', sa.Integer(), nullable=True),
    sa.Column('monthly_burn_rate', sa.Integer(), nullable=True),
    sa.Column('runway_months', sa.Integer(), nullable=True),
    sa.Column('total_raised', sa.Integer(), nullable=True),
    sa.Column('previous_investors', sa.Text(), nullable=True),
    sa.Column('market_size', sa.String(length=20), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('monthly_growth_rate', sa.Float(), nullable=True),
    sa.Column('founder_names', sa.Text(), nullable=True),
    sa.Column('key_team_members', sa.Text(), nullable=True),
    sa.Column('advisors', sa.Text(), nullable=True),
    sa.Column('headquarters', sa.String(length=100), nullable=True),
    sa.Column('legal_structure', sa.String(length=50), nullable=True),
    sa.Column('intellectual_property', sa.Text(), nullable=True),
    sa.Column('fund_usage_plan', sa.Text(), nullable=True),
    sa.Column('awards_recognition', sa.Text(), nullable=True),
    sa.Column('press_coverage', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('match_notifications', sa.Boolean(), nullable=True),
    sa.Column('weekly_digest', sa.Boolean(), nullable=True),
    sa.Column('profile_visibility', sa.String(length=20), nullable=True),
    sa.Column('contact_sharing', sa.Boolean(), nullable=True),
    sa.Column('auto_matching', sa.Boolean(), nullable=True),
    sa.Column('match_frequency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('overall_explanation', sa.Text(), nullable=True),
    sa.Column('industry_analysis', sa.Text(), nullable=True),
    sa.Column('industry_score', sa.Float(), nullable=True),
    sa.Column('industry_reasons', sa.Text(), nullable=True),
    sa.Column('funding_analysis', sa.Text(), nullable=True),
    sa.Column('funding_score', sa.Float(), nullable=True),
    sa.Column('funding_reasons', sa.Text(), nullable=True),
    sa.Column('geographic_analysis', sa.Text(), nullable=True),
    sa.Column('geographic_score', sa.Float(), nullable=True),
    sa.Column('geographic_reasons', sa.Text(), nullable=True),
    sa.Column('experience_analysis', sa.Text(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('experience_reasons', sa.Text(), nullable=True),
    sa.Column('market_analysis', sa.Text(), nullable=True),
    sa.Column('market_score', sa.Float(), nullable=True),
    sa.Column('market_reasons', sa.Text(), nullable=True),
    sa.Column('risk_analysis', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('mitigation_suggestions', sa.Text(), nullable=True),
    sa.Column('synergy_analysis', sa.Text(), nullable=True),
    sa.Column('synergy_opportunities', sa.Text(), nullable=True),
    sa.Column('value_add_potential', sa.Text(), nullable=True),
    sa.Column('success_probability', sa.Float(), nullable=True),
    sa.Column('success_factors', sa.Text(), nullable=True),
    sa.Column('success_timeline', sa.String(length=50), nullable=True),
    sa.Column('similar_successful_matches', sa.Text(), nullable=True),
    sa.Column('market_precedents', sa.Text(), nullable=True),
    sa.Column('recommended_actions', sa.Text(), nullable=True),
    sa.Column('conversation_starters', sa.Text(), nullable=True),
    sa.Column('due_diligence_focus', sa.Text(), nullable=True),
    sa.Column('algorithm_confidence', sa.Float(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('insight_quality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_insights')
    op.drop_table('user_preferences')
    op.drop_table('startup_profiles')
    op.drop_table('matches')
    op.drop_table('investor_profiles')
    # ### end Alembic commands ###
